DEBIAN-X86_DIR ?= .

debian-x86_packages:
	bash ${DEBIAN-X86_DIR}/packages/install.sh

debian-x86_files:
	bash ${DEBIAN-X86_DIR}/files/install.sh

debian-x86_config:
	bash ${DEBIAN-X86_DIR}/config/install.sh
