DEBIAN-ARM64_DIR ?= .

debian-arm64_packages:
	cd ${DEBIAN-ARM64_DIR}/packages; ./install.sh

debian-arm64_files:
	cd ${DEBIAN-ARM64_DIR}/files; ./install.sh

debian-arm64_config:
	cd ${DEBIAN-ARM64_DIR}/config; ./install.sh
