DEBIAN-ARM_DIR ?= .

debian-arm_packages:
	cd ${DEBIAN-ARM_DIR}/packages; ./install.sh

debian-arm_files:
	cd ${DEBIAN-ARM_DIR}/files; ./install.sh

debian-arm_config:
	cd ${DEBIAN-ARM_DIR}/config; ./install.sh
