DEBIAN-AMD64_DIR ?= .

debian-amd64_packages:
	cd ${DEBIAN-AMD64_DIR}/packages; ./install.sh

debian-amd64_files:
	cd ${DEBIAN-AMD64_DIR}/files; ./install.sh

debian-amd64_config:
	cd ${DEBIAN-AMD64_DIR}/config; ./install.sh
